version: '3.8'
services:
  mysqldb:
    image: mysql:latest
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$PASSWORD_DB
      - MYSQL_DATABASE=$DATABASE_NAME
    ports:
      - 3306:3306
  
  app:
    build: .
    depends_on: 
      - mysqldb
    links: 
      - mysqldb
    ports: 
      - 3000:3000


